AWSTemplateFormatVersion: '2010-09-09'
Description: Creating s3 buckets and lamda fuction to copy the files.
Resources:
  LambdaFunResource:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: copy-data-to-s3bucket
      Code:
        S3Bucket: kazim-temp-bucket
        S3Key: lambda_function_test.zip
      Description: Used to run job
      Handler: lambda_function_test.lambda_handler
      Role: !ImportValue StepLamdaS3CopyingRole
      Runtime: python3.6
      Timeout: 120
  
  FirstStateMachineDemo:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      DefinitionString:
        !Sub
          - |-
            {
              "Comment": "A Hello World example using an AWS Lambda function",
              "StartAt": "LamdaCopyFunctionStep",
              "States": {
                "LamdaCopyFunctionStep": {
                  "Type": "Task",
                  "Resource": "${lambdaArn}",
                  "End": true
                }
              }
            }
          - {lambdaArn: !GetAtt [ LambdaFunResource, Arn ]}
      RoleArn: !ImportValue StatesExecutionRole
  
  rLambdaScheduledRule:
    Type: "AWS::Events::Rule"
    Properties: 
      Description: "CloudWatch Event to trigger lambda fn"
      ScheduleExpression: "rate(1 minute)"
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt LambdaFunResource.Arn
          Id: "targetevent_v1"

  PermissionForEventsToInvokeLambda: 
    Type: "AWS::Lambda::Permission"
    Properties: 
      FunctionName: !GetAtt LambdaFunResource.Arn
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - rLambdaScheduledRule
          - Arn